title: KiCad-Master-Lib
description: >
  A FEASTorg project page for KiCad-Master-Lib.
baseurl: "/KiCad-Master-Lib"  
url: "https://feastorg.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
# Don't publish these
exclude:
  - .github
  - TODO.md

# automatically apply layout: page to all docs/*.md
defaults:
  -
    scope:
      path: ""         # everything under docs/
      type: "pages"
    values:
      layout: "page"
